# Generated by Django 6.0.5 on 2026-06-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField()),
                ('translation', models.TextField(blank=True)),
                ('deck', models.CharField(choices=[('geral', 'Geral'), ('frases', 'Frases do dia a dia'), ('phrasal', 'Phrasal Verbs'), ('vocab', 'Vocabulário')], default='geral', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
