# Generated by Django 6.0.5 on 2026-06-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.TextField()),
                ('pt', models.TextField(blank=True)),
                ('video_id', models.CharField(blank=True, db_index=True, max_length=20)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('validada', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
    ]
