# Generated by Django 5.2.15 on 2026-06-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensao', '0004_alter_capturedsentence_id_alter_flashcard_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturedsentence',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
