# Generated by Django 6.0.5 on 2026-06-15 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensao', '0006_video_studycard'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='status',
            field=models.CharField(choices=[('new', 'Novo'), ('learning', 'Aprendendo'), ('reviewed', 'Revisado')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcards', to='extensao.video'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='deck',
            field=models.CharField(choices=[('geral', 'Geral'), ('frases', 'Frases do dia a dia'), ('phrasal', 'Phrasal Verbs'), ('vocab', 'Vocabulário'), ('video', 'Do vídeo')], default='geral', max_length=30),
        ),
        migrations.DeleteModel(
            name='StudyCard',
        ),
    ]
