# Generated by Django 5.2.15 on 2026-06-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensao', '0007_flashcard_progress_flashcard_status_flashcard_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='source_video_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
