# Generated by Django 5.2.15 on 2026-06-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensao', '0009_backfill_flashcard_source_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturedsentence',
            name='video_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='capturedsentence',
            name='video_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
