# Generated by Django 5.2.15 on 2026-06-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensao', '0010_capturedsentence_video_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='video_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='video_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
