# Generated by Django 5.2.15 on 2026-07-01 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extensao', '0010_deck_flashcard_deck_obj'),
        ('extensao', '0012_backfill_flashcard_video_title_url'),
    ]

    operations = [
    ]
